spring.application.name=meerkatai
jwt.secret=${JWT_SECRET_KEY}
spring.profiles.active=local

# ? Naver SMTP ?? (??? ?? ?? ??)
# ??? ???? ?? ??? ???
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${APP_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8

# AWS Region
cloud.aws.region.static=ap-northeast-2

# EC2 ?? ?? ????
cloud.aws.stack.auto=false

# S3 Bucket Name (???????? ??? ?? ??)
aws.s3.bucket-name=cctv-recordings-yuhan-20250505
cloud.aws.s3.bucket=cctv-recordings-yuhan-20250505

# (?? ??) EC2 ???? ???? ?? ?? ?? ??? ???? ?? ??
# ?? ?? ??? ????, ???? ????? IAM ??? ?????.
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# Pre-signed URL ?? ?? (? ??)}
aws.s3.presigned-url.expiration-minutes=1440


# ?? ? ??? ?? Prefix
aws.s3.video-prefix=clips/
aws.s3.thumbnail-prefix=thumbnails/ # ???? ??? ??

# 빈 정의 오버라이딩 허용 설정
spring.main.allow-bean-definition-overriding=true

server.port=8080

# Dialogflow settings
dialogFlow.projectId=symmetric-stage-472117-n3

# Nginx ??? ??? ??? ??? ?, Spring Boot? application.properties? ??? ??:
server.forward-headers-strategy=NATIVE

# ?? SSL ?? ??? Nginx ?? ? Spring Boot?? ?? ?? (?? ??)
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=...
# server.ssl.key-store-password=...
# server.ssl.key-alias=...
