# Lightsail Instance Internal MySQL - DEV Profile
spring.datasource.url=jdbc:mysql://localhost:3306/meerkatai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=meerkatuser
spring.datasource.password=${DB_DEV_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings for DEV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# ?? ?? (?? ??, ???? 8080)
server.port=8080

